# Generated by Django 2.0.4 on 2018-04-26 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='Access Token')),
                ('expires_in', models.IntegerField(verbose_name='Access Token有效期(单位秒)')),
                ('expires_date', models.DateTimeField(verbose_name='Access Token过期时间')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('say', models.CharField(max_length=100, verbose_name='返回对话')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='置信度')),
                ('action_id', models.CharField(max_length=100, verbose_name='动作名称,fail_action未命中任何意图')),
                ('action_type', models.TextField(verbose_name='动作类型')),
                ('arg_list', models.TextField(help_text='只当action是做意图或词槽澄清的时候,这里才会赋值;"string"通常是意图or词槽名称', verbose_name='动作参数')),
                ('hint_list', models.TextField(help_text='如果当前动作有引导或faq问答中存在多个question需要进一步澄清,则该域存在', verbose_name='动作引导选项')),
            ],
        ),
        migrations.CreateModel(
            name='BotMergedSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='词槽置信度')),
                ('original_word', models.CharField(max_length=100, verbose_name='原始词槽值')),
                ('normalized_word', models.CharField(max_length=100, verbose_name='词槽归一后的值')),
                ('type', models.CharField(max_length=100, verbose_name='词槽类型')),
            ],
            options={
                'verbose_name': '词槽列表',
                'verbose_name_plural': '词槽列表',
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='输入语句')),
                ('current_qu_intent', models.CharField(max_length=100, verbose_name='当前意图')),
                ('intent_confidence', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='意图置信度')),
            ],
            options={
                'verbose_name': '解析的意图',
                'verbose_name_plural': '解析的意图',
            },
        ),
        migrations.CreateModel(
            name='IntentCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_candidate', models.CharField(max_length=100, verbose_name='候选意图')),
                ('intent_confidence', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='意图置信度')),
                ('slots', models.TextField(verbose_name='词槽列表')),
                ('intent_need_clarify', models.BooleanField(verbose_name='意图是否需要澄清')),
                ('from_who', models.CharField(max_length=100, verbose_name='哪个qu出的结果')),
                ('match_info', models.CharField(max_length=100, verbose_name='匹配信息,比如匹配了哪个模板')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='app.Intent', verbose_name='关联意图')),
            ],
            options={
                'verbose_name': '意图候选项',
                'verbose_name_plural': '意图候选项',
            },
        ),
        migrations.CreateModel(
            name='LexicalAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_word', models.TextField(verbose_name='当前term的基础粒度分词')),
                ('type', models.CharField(max_length=100, verbose_name='NER类型')),
                ('term', models.CharField(max_length=100, verbose_name='当前term')),
                ('weight', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='重要性,所有term重要性之和为1')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexicons', to='app.Intent', verbose_name='关联意图')),
            ],
            options={
                'verbose_name': '词法分析结果',
                'verbose_name_plural': '词法分析结果',
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(verbose_name='情感分析倾向 0表示负向 1表示中性 2表示正向')),
                ('pval', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='好评置信度-差评置信度, 越大表示分类结果的可靠性越高，0-1之间的值')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='app.Intent', verbose_name='关联意图')),
            ],
            options={
                'verbose_name': '情感分析结果',
                'verbose_name_plural': '情感分析结果',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_id', models.IntegerField(verbose_name='场景ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='会话ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '会话',
                'verbose_name_plural': '会话列表',
            },
        ),
        migrations.AddField(
            model_name='intent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='app.Session', verbose_name='关联会话'),
        ),
        migrations.AddField(
            model_name='botmergedslot',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='app.Intent', verbose_name='关联意图'),
        ),
        migrations.AddField(
            model_name='action',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='app.Intent', verbose_name='关联意图'),
        ),
    ]
