# Generated by Django 2.0.4 on 2018-05-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180507_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(max_length=100, verbose_name='会话ID'),
        ),
    ]
