# Generated by Django 2.0.4 on 2018-05-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180511_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='confidence',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='置信度'),
        ),
        migrations.AlterField(
            model_name='botmergedslot',
            name='confidence',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='词槽置信度'),
        ),
        migrations.AlterField(
            model_name='intent',
            name='intent_confidence',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='意图置信度'),
        ),
        migrations.AlterField(
            model_name='intentcandidate',
            name='intent_confidence',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='意图置信度'),
        ),
    ]
