# Generated by Django 2.0.4 on 2018-05-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180514_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='main_exe',
            field=models.CharField(default='', max_length=20, verbose_name='执行函数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='say',
            field=models.CharField(max_length=20, verbose_name='返回对话'),
        ),
    ]
