# Generated by Django 2.0.4 on 2018-05-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180515_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='interval',
            field=models.CharField(blank=True, max_length=100, verbose_name='时间段'),
        ),
        migrations.AddField(
            model_name='intent',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='查询的url'),
        ),
    ]
