# Generated by Django 2.0.4 on 2018-05-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180517_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='url',
            field=models.TextField(blank=True, verbose_name='查询的url'),
        ),
    ]
