# Generated by Django 2.0.4 on 2018-05-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180517_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botmergedslot',
            options={'ordering': ['intent', 'confidence'], 'verbose_name': '词槽列表', 'verbose_name_plural': '词槽列表'},
        ),
    ]
