# Generated by Django 2.0.4 on 2018-05-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180521_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmergedslot',
            name='length',
            field=models.IntegerField(default=0, verbose_name='字节总量'),
        ),
        migrations.AddField(
            model_name='botmergedslot',
            name='offset',
            field=models.IntegerField(default=0, verbose_name='字节偏移值'),
        ),
    ]
