# Generated by Django 2.0.4 on 2018-05-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180524_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentcandidate',
            name='match_info',
            field=models.CharField(max_length=256, verbose_name='匹配信息,比如匹配了哪个模板'),
        ),
    ]
