# Generated by Django 2.0.4 on 2018-06-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180529_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='agent',
            field=models.CharField(default='WECHAT', max_length=32, verbose_name='代理来源'),
        ),
    ]
