# Generated by Django 2.0.4 on 2018-06-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_intent_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intent',
            name='agent',
        ),
    ]
